sugarcrm:
  image: devtac-sugar77:latest
  command: apache2-foreground
  links:
    - mysql_crm
    - elasticsearch_crm
  volumes:
    - .:/app
  ports:
    - "8082:80"

mysql_crm:
  image: mysql:5.6
  ports:
    - "3307:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=sugarcrm
    - MYSQL_USER=sugarcrm
    - MYSQL_PASSWORD=sugarcrm
  volumes:
    - ./docker/config/mysql:/etc/mysql/conf.d
    - ./docker/data/mysql:/var/lib/mysql

elasticsearch_crm:
  image: elasticsearch:1.7.5
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - ./docker/config/elasticsearch:/usr/share/elasticsearch/config
